---
# Installation tasks for Red Hat Linux
- name: Download the Splunk package (Enterprise Linux)
  ansible.builtin.get_url:
    url: "{{ splunk_rpm }}"
    dest: "/tmp/{{ splunk_forwarder_rpm }}"
    checksum: "{{ splunk_rpm_checksum }}"
    mode: 0664

- name: Install Splunk (python2 yum)
  ansible.builtin.yum:
    name: "/tmp/{{ splunk_forwarder_rpm }}"
    state: present
  when: ansible_facts.python.version.major | int < 3

- name: Install Splunk (python3 dnf)
  ansible.builtin.dnf:
    name: "/tmp/{{ splunk_forwarder_rpm }}"
    disable_gpg_check: true
    state: present
  when: ansible_facts.python.version.major | int >= 3
