---
# Install splunk using distribution's package manager

- name: Ensure Splunk Forwarder using APT package manager
  ansible.builtin.apt:
    name: "{{ splunk_forwarder_packages }}"
    state: present
  when: ansible_facts.os_family == 'Debian'

- name: Ensure Splunk Forwarder using DNF package manager
  ansible.builtin.dnf:
    name: "{{ splunk_forwarder_packages }}"
    disable_gpg_check: true
    state: present
  when: ansible_facts.os_family == 'RedHat'
